pipeline {
    agent any

    stages {

        stage('Check Workspace') {
            steps {
                bat 'echo Jenkins is running'
                bat 'dir'
            }
        }

        stage('Build Docker Images') {
            steps {
                bat 'docker-compose build'
            }
        }

        stage('Run Containers') {
            steps {
                bat 'docker-compose up -d'
            }
        }

        stage('Verify Containers') {
            steps {
                bat 'docker ps'
            }
        }
    }
}